name: Build Plugin

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: microsoft/setup-msbuild@v2
    
    - name: Clone SDK
      run: git clone https://github.com/bakkesmodorg/BakkesModSDK.git C:\bakkesmodsdk
    
    - name: Configure
      run: |
        cmake -B build -G "Visual Studio 17 2022" -A x64 -DBAKKESMOD_PLUGIN_SDK_DIR=C:\bakkesmodsdk
    
    - name: Build
      run: cmake --build build --config Release
    
    - name: Package
      run: |
        mkdir output
        copy build\Release\RollLockGhost.dll output\
        copy plugin.cfg output\
      shell: cmd
    
    - uses: actions/upload-artifact@v4
      with:
        name: RollLockGhost
        path: output/
